export const seedCategories = [
  {
    name: 'Oversized Printed Tees',
    slug: 'oversized-printed-tees',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    description: '240 GSM bio-washed 100% Indian cotton boxy fit graphic tees',
  },
  {
    name: 'Desi Vibe Typography',
    slug: 'desi-vibe-typography',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    description: 'Quirky Indian typography & desi quotes DTF prints',
  },
  {
    name: 'Anime & Pop Culture',
    slug: 'anime-pop-culture',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    description: 'Handcrafted anime illustrations, manga art & retro gaming prints',
  },
  {
    name: 'Minimalist Line Art',
    slug: 'minimalist-line-art',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    description: 'Subtle self-made line art, geometric vector prints & aesthetic tees',
  },
  {
    name: 'Self-Made Artist Drops',
    slug: 'self-made-artist-drops',
    image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=800&q=80',
    description: 'Limited edition handcrafted graphic t-shirts designed in India',
  },
];

export const seedProducts = [
  {
    _id: 'seed_prod_1',
    name: 'Cyberpunk Neon Printed Oversized Tee',
    slug: 'cyberpunk-neon-printed-oversized-tee',
    description: 'Hand-designed futuristic neon graphic printed on 240 GSM 100% bio-washed Indian combed cotton. Features dropped shoulders, boxy fit, and high-density screen print.',
    category: 'Oversized Printed Tees',
    gender: 'Men',
    price: 699,
    originalPrice: 999,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Pitch Black', hex: '#0f172a' },
      { name: 'Washed Charcoal', hex: '#334155' },
      { name: 'Off White', hex: '#f8fafc' },
    ],
    stock: 50,
    ratings: 4.9,
    numReviews: 48,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    ],
    discountPercentage: 30,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
  },
  {
    _id: 'seed_prod_2',
    name: 'Desi Swagger Hindi Typography Printed Tee',
    slug: 'desi-swagger-hindi-typography-printed-tee',
    description: 'Bold custom Hindi typography screen-printed with soft puff ink. Made from 100% super-combed Indian cotton, lightweight, soft, and breathable.',
    category: 'Desi Vibe Typography',
    gender: 'Men',
    price: 599,
    originalPrice: 899,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Royal Navy', hex: '#1e3a8a' },
      { name: 'Chalk White', hex: '#f8fafc' },
      { name: 'Mustard Yellow', hex: '#d97706' },
    ],
    stock: 35,
    ratings: 4.8,
    numReviews: 32,
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    discountPercentage: 33,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
  },
  {
    _id: 'seed_prod_3',
    name: 'Demon Samurai Anime Printed Graphic Shirt',
    slug: 'demon-samurai-anime-printed-graphic-shirt',
    description: 'Self-made custom Japanese anime artwork printed across the back with chest icon detail. Premium DTF print that won\'t fade after 50+ washes.',
    category: 'Anime & Pop Culture',
    gender: 'Men',
    price: 749,
    originalPrice: 1099,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Jet Black', hex: '#000000' },
      { name: 'Crimson Red', hex: '#991b1b' },
    ],
    stock: 40,
    ratings: 4.95,
    numReviews: 64,
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    discountPercentage: 32,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
  },
  {
    _id: 'seed_prod_4',
    name: 'Aesthetic Line Art Abstract Face Printed Tee',
    slug: 'aesthetic-line-art-abstract-face-printed-tee',
    description: 'Minimalist continuous line art design printed with high-density DTF ink. Super soft bio-washed fabric for everyday style.',
    category: 'Minimalist Line Art',
    gender: 'Women',
    price: 649,
    originalPrice: 899,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Sand Beige', hex: '#d97706' },
      { name: 'Sage Green', hex: '#3f6212' },
      { name: 'Off White', hex: '#f8fafc' },
    ],
    stock: 25,
    ratings: 4.75,
    numReviews: 21,
    images: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    ],
    discountPercentage: 28,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
  },
  {
    _id: 'seed_prod_5',
    name: 'Self-Made Original Artist Edition Printed Tee',
    slug: 'self-made-original-artist-edition-printed-tee',
    description: 'Exclusive self-made artwork produced in limited quantities of 100 pieces per batch. Comes with numbered neck label and custom artist signature print.',
    category: 'Self-Made Artist Drops',
    gender: 'Women',
    price: 799,
    originalPrice: 1199,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Vintage Black', hex: '#1e293b' },
      { name: 'Olive Green', hex: '#365314' },
    ],
    stock: 15,
    ratings: 4.9,
    numReviews: 38,
    images: [
      'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    discountPercentage: 33,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
  },
];

export const seedCoupons = [
  {
    code: 'WELCOME20',
    discountType: 'percentage',
    discountValue: 20,
    minPurchase: 999,
    expirationDate: new Date('2027-12-31'),
    isActive: true,
  },
  {
    code: 'GRIZZLE100',
    discountType: 'fixed',
    discountValue: 100,
    minPurchase: 799,
    expirationDate: new Date('2027-12-31'),
    isActive: true,
  },
  {
    code: 'DESI50',
    discountType: 'fixed',
    discountValue: 50,
    minPurchase: 499,
    expirationDate: new Date('2027-12-31'),
    isActive: true,
  },
];
